FROM quay.io/centos/centos:stream9

RUN curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/CentOS_8/devel:kubic:libcontainers:stable.repo

RUN INSTALL_PKGS="vim wget jq python3 git net-tools iptables iproute pciutils ethtool httpd iperf3 tcpdump sysstat ipmitool util-linux" && yum install -y ${INSTALL_PKGS}

RUN wget -c https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.1/crictl-v1.26.1-linux-amd64.tar.gz -O - | tar -xz \
    && mv crictl /usr/bin/crictl


CMD ["/bin/bash"]
